# Generated by Django 5.2.15 on 2026-06-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('services', 'Services'), ('team', 'Team'), ('join_us', 'Join Us')], help_text='Select the page this SEO record belongs to.', max_length=50, unique=True, verbose_name='Page')),
                ('meta_title', models.CharField(help_text='Recommended: 50–70 characters. Shown in browser tab & Google results.', max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.TextField(help_text='Recommended: 120–160 characters. Shown below the title in Google.', max_length=160, verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(blank=True, help_text='Comma-separated keywords (optional, low SEO impact today).', verbose_name='Meta Keywords')),
                ('author', models.CharField(blank=True, default='Onion Techs', max_length=100, verbose_name='Author')),
                ('canonical_url', models.URLField(blank=True, help_text='Full URL, e.g. https://oniontechs.com/about/  — leave blank to skip.', verbose_name='Canonical URL')),
                ('robots_meta', models.CharField(choices=[('index, follow', 'Index, Follow (default)'), ('noindex, follow', 'No-Index, Follow'), ('index, nofollow', 'Index, No-Follow'), ('noindex, nofollow', 'No-Index, No-Follow')], default='index, follow', help_text='Controls how search-engine crawlers index this page.', max_length=50, verbose_name='Robots Meta')),
                ('og_title', models.CharField(blank=True, help_text='Leave blank to fall back to Meta Title.', max_length=95, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, help_text='Leave blank to fall back to Meta Description.', max_length=200, verbose_name='OG Description')),
                ('og_type', models.CharField(choices=[('website', 'Website'), ('article', 'Article'), ('profile', 'Profile'), ('product', 'Product')], default='website', max_length=20, verbose_name='OG Type')),
                ('og_image', models.ImageField(blank=True, help_text='Recommended size: 1200×630 px. Used when shared on social media.', null=True, upload_to='seo/og_images/', verbose_name='OG Image')),
                ('twitter_card', models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image (recommended)'), ('app', 'App'), ('player', 'Player')], default='summary_large_image', max_length=30, verbose_name='Twitter Card Type')),
                ('twitter_title', models.CharField(blank=True, help_text='Leave blank to fall back to Meta Title.', max_length=70, verbose_name='Twitter Title')),
                ('twitter_description', models.TextField(blank=True, help_text='Leave blank to fall back to Meta Description.', max_length=200, verbose_name='Twitter Description')),
                ('twitter_image', models.ImageField(blank=True, help_text='Leave blank to reuse OG Image.', null=True, upload_to='seo/twitter_images/', verbose_name='Twitter Image')),
                ('schema_json', models.TextField(blank=True, help_text='Paste valid JSON-LD structured data here. It is injected as-is inside a <script type="application/ld+json"> tag.', verbose_name='Schema / JSON-LD')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Page SEO',
                'verbose_name_plural': 'Pages SEO',
                'ordering': ['page_name'],
            },
        ),
    ]
