# Generated by Django 5.2.15 on 2026-06-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Job Title')),
                ('description', models.TextField(help_text='Brief role description shown on the listing.', verbose_name='Description')),
                ('skills', models.CharField(help_text='Comma-separated, e.g. React, TypeScript, Next.js', max_length=500, verbose_name='Required Skills')),
                ('location_type', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], default='remote', max_length=20, verbose_name='Location Type')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from website.', verbose_name='Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Job Opening',
                'verbose_name_plural': 'Job Openings',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Service Title')),
                ('slug', models.SlugField(help_text='Auto-generated from title. Used in URL: /services/your-slug/', unique=True, verbose_name='URL Slug')),
                ('icon', models.CharField(default='💻', help_text='Single emoji used as the service icon.', max_length=10, verbose_name='Icon (Emoji)')),
                ('short_description', models.TextField(help_text='Shown on the Services listing page card (max 250 chars).', max_length=250, verbose_name='Short Description')),
                ('full_description', models.TextField(help_text='Detailed content for the individual service page.', verbose_name='Full Description')),
                ('features', models.TextField(blank=True, help_text='One feature per line. Shown as bullet points on the detail page.', verbose_name='Key Features')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('meta_title', models.CharField(help_text='50–70 characters. Shown in Google search results.', max_length=70, verbose_name='Meta Title')),
                ('meta_description', models.TextField(help_text='120–160 characters. Shown below title in Google.', max_length=160, verbose_name='Meta Description')),
                ('meta_keywords', models.TextField(blank=True, verbose_name='Meta Keywords')),
                ('canonical_url', models.URLField(blank=True, help_text='e.g. https://oniontechs.com/services/web-applications/', verbose_name='Canonical URL')),
                ('og_title', models.CharField(blank=True, help_text='Blank = use Meta Title', max_length=95, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, help_text='Blank = use Meta Description', max_length=200, verbose_name='OG Description')),
                ('og_image', models.ImageField(blank=True, help_text='1200×630 px recommended.', null=True, upload_to='seo/services/', verbose_name='OG Image')),
                ('schema_json', models.TextField(blank=True, verbose_name='Schema / JSON-LD')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('role', models.CharField(max_length=150, verbose_name='Role / Title')),
                ('bio', models.TextField(help_text='Short biography shown on the team card.', verbose_name='Bio')),
                ('photo', models.ImageField(blank=True, help_text='Square image, at least 400×400 px recommended.', null=True, upload_to='team/photos/', verbose_name='Profile Photo')),
                ('category', models.CharField(choices=[('leadership', 'Leadership Team'), ('core', 'Core Team')], default='leadership', max_length=20, verbose_name='Category')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfolio URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower = shown first.', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from website.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='canonical_url',
            field=models.URLField(blank=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='meta_description',
            field=models.TextField(help_text='120–160 chars', max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='meta_keywords',
            field=models.TextField(blank=True, verbose_name='Meta Keywords'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='meta_title',
            field=models.CharField(help_text='50–70 chars', max_length=70, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='og_description',
            field=models.TextField(blank=True, max_length=200, verbose_name='OG Description'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='og_image',
            field=models.ImageField(blank=True, help_text='1200×630 px', null=True, upload_to='seo/og_images/', verbose_name='OG Image'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='og_title',
            field=models.CharField(blank=True, max_length=95, verbose_name='OG Title'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='page_name',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('services', 'Services'), ('team', 'Team'), ('join_us', 'Join Us')], max_length=50, unique=True, verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='robots_meta',
            field=models.CharField(choices=[('index, follow', 'Index, Follow (default)'), ('noindex, follow', 'No-Index, Follow'), ('index, nofollow', 'Index, No-Follow'), ('noindex, nofollow', 'No-Index, No-Follow')], default='index, follow', max_length=50, verbose_name='Robots Meta'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='schema_json',
            field=models.TextField(blank=True, verbose_name='Schema / JSON-LD'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='twitter_description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Twitter Description'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='twitter_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/twitter_images/', verbose_name='Twitter Image'),
        ),
        migrations.AlterField(
            model_name='pageseo',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='Twitter Title'),
        ),
    ]
