# Generated by Django 5.2.15 on 2026-06-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jobopening_service_teammember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='skills',
            field=models.CharField(blank=True, help_text='Comma-separated skills, e.g. Python, React, AWS', max_length=255, verbose_name='Skills'),
        ),
    ]
