# Generated by Django 5.2.15 on 2026-06-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teammember_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='High quality image for the service card.', null=True, upload_to='services/covers/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='category',
            field=models.CharField(choices=[('leadership', 'Leadership Team'), ('core', 'Core Team'), ('internship', 'Interns / Trainees')], default='leadership', max_length=20, verbose_name='Category'),
        ),
    ]
