# Generated by Django 5.2.15 on 2026-06-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_cover_image_alter_teammember_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Onion Techs', max_length=100)),
                ('email', models.EmailField(default='info@oniontechs.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='+1 (555) 123-4567', max_length=30, null=True)),
                ('address', models.TextField(blank=True, default='123 Tech Street, Silicon Valley, CA', null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
